### ISSUE TITLE
TS 적용 : 유지보수와 예측이 쉬운 코드 작성을 위한 정적 타이핑 TS 적용

### ISSUE THREAD

**Issue by wndudqus** [squad-b/work-assistant-web#62]
**as is** 
js 는 자유도가 높지만 코드 유지보수 측면에서 예측이 어렵고 타입 추론등의 기능 사용이 불가능합니다.
현재 프론트 프로젝트에서 js 를 사용하고 있습니다.

**tobe**
프로젝트에 TS를 적용해서 예측과 유지보수가 쉬운 코드를 작성

[ts 장점](https://joshua1988.github.io/ts/why-ts.html#%EC%99%9C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8%EB%A5%BC-%EC%8D%A8%EC%95%BC%ED%95%A0%EA%B9%8C%EC%9A%94)

**Comment by jhlee910609** [comment]
이거 언제쯤 머지할 예정인가요?

**Comment by wndudqus** [comment]
아 아직 진행을 못했는데 오늘 중으로 작업해서 머지해보도록 하겠습니다.
